server:
  port: 8082
spring:
  application:
    name: ERPSystem-phase3-Common
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000 # 유휴 연결을 30초 후 종료
      max-lifetime: 1800000 # 연결 수명을 30분으로 제한
      leak-detection-threshold: 2000 # 2초 이상 반환되지 않는 연결 로그 출력
    writer:
      driver-class-name: com.mysql.cj.jdbc.Driver
    reader:
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true #신규
        dialect: org.hibernate.dialect.MySQLDialect
        multi-tenancy: SCHEMA # 멀티 테넌시 설정 (스키마 기반)
        tenant_identifier_resolver: com.megazone.ERPSystem_phase3_Common.common.config.multi_tenant.SchemaBasedTenantIdentifierResolver
        multi_tenant_connection_provider: com.megazone.ERPSystem_phase3_Common.common.config.multi_tenant.SchemaBasedMultiTenantConnectionProvider
    show-sql: false # SQL 쿼리를 콘솔에 출력하도록 설정
    defer-datasource-initialization: true # 데이터베이스 초기화를 지연시켜, 스키마 생성 후 데이터 초기화가 이루어지도록 설정
  web:
    resources:
      static-locations:
        - 'classpath:/static/' # 정적 리소스 위치 지정 (클래스패스 기준)
        - 'classpath:/public/' # 정적 리소스 위치 지정 (클래스패스 기준)
        - 'classpath:/resources/' # 정적 리소스 위치 지정 (클래스패스 기준)
        - 'classpath:/META-INF/resources/' # 정적 리소스 위치 지정 (클래스패스 기준)
        - 'file:src/main/frontend/dist/' # 정적 리소스 위치 지정 (파일 시스템 기준)
  flyway:
    enabled: false

  sql:
    init:
      mode: never
      data-locations:
        - classpath:initial-database/financial/common/financial_contact.sql
        - classpath:initial-database/financial/company/company_address.sql
        - classpath:initial-database/financial/company/company_tax_office.sql
        - classpath:initial-database/financial/company/company_main_business.sql
        - classpath:initial-database/financial/company/company_corporate_kind.sql
        - classpath:initial-database/financial/company/company_corporate_type.sql
        - classpath:initial-database/financial/company/company_representative.sql
        - classpath:initial-database/financial/company/company.sql
        - classpath:initial-database/hr/employee.sql
        - classpath:initial-database/hr/users.sql
        - classpath:initial-database/environmental_certification_assessment.sql


logging:
  level:
#    root: DEBUG
    root: INFO
#    com.megazone: DEBUG
#    org.flywaydb: DEBUG
#    org.hibernate.boot.model.naming: TRACE
#    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %highlight(%-5level) %logger{36} - %msg%n"